config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  get 'terms' => 'about#terms'
  get 'about' => 'about#about'
  resources :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
	validates :content, presence: true
  has_many :comments, dependent: :destroy
  belongs_to :user, optional: true
  validates :title, length: { maximum: 140 }
  validates :content, length: { maximum: 4000 }

  def subject
    title
  end

  def last_comment
    comments.last
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true
  validates :body, length: { maximum: 4000 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :articles, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def terms
  end

  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :authenticate_user!, :only => [:create, :edit, :destroy, :new]

def show
  @article = Article.find(params[:id])
  @user = User.find(@article.user_id)
end

def index
  @articles = Article.all
end

def new
end

  def create
    @article = Article.new(params_article.merge(user_id: current_user.id))
    if @article.valid?
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

def edit 
  @article = Article.find(params[:id])
end

def update
  @article = Article.find(params[:id])
  if @article.update(params_article)
    redirect_to @article
  else
    render action: 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
  redirect_to articles_path
end

  private
  def params_article
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  private
  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(params_contact)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private
  def params_contact
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
  def index
    @users = User.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/about.html.erb
<!DOCTYPE html>
<html>
<head>

</head

<body>
<div class="container">
<h3 style="color: #999">About us</h3>
</div>
</body>
</html>

app/views/about/index.html.erb
<h3>About Us</h3>

app/views/about/terms.html.erb
<h2>terms</h2>

app/views/articles/edit.html.erb
<div class="container">
<h5>Edit article</h5>

<%= form_for :article, url: article_path(@article), method: :put do |f|%>
<p>
  <%= f.label :title%><br/>
  <%= f.text_field :title, :class => "form-control"%>
</p>
<p>
 <label for="article_content">Article</label><br/>
  <%= f.text_area :content, :class => "form-control"%>
</p>
<p>
  <%= f.submit :class => "btn btn-warning btn-sm"%>
</p>
<%end%>
</div>

app/views/articles/index.html.erb
<div class="container">
<% @articles.each do |article| %>
<h2><%=article.title%></h2>
<div><%=article.content%></div>
<%user = article.user%>
<a href="<%=article_path(article)%>" class="badge badge-dark">Show</a>
<i style="color: #777; position: absolute; right: 10%;">posted by <a style="color: #777;" href="<%#%>" ><%=user.username%></a></i>
<hr/>
<%end%>
</div>

app/views/articles/new.html.erb
<div class="container">
<h3><%=t('articles.create')%></h3>

<%= form_for :article, url: '/articles' do |f|%>
<p>
  <%= f.label :title%><br/>
  <%= f.text_field :title, :class => "form-control"%>
</p>
<p>
 <label for="article_content">Article</label><br/>
  <%= f.text_area :content, :class => "form-control"%>
</p>
<p>
  <%= f.submit%>
</p>
<%end%>
</div>

app/views/articles/show.html.erb
<head>
</head>

<body>

<div class="container">
<div class="alert alert-warning" role="alert">

<h3><%=@article.title%></h3>
<div><%=@article.content%></div>
<div>posted by <a href="<%=@user%>"><%=@user.username%></a></div>


<%if current_user%>
<%if current_user.username == @user.username%>
<a href="<%=edit_article_path(@article)%>" class="badge badge-dark">Edit</a> 
<%= button_to 'Delete', article_path(@article), :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' }%>
<%end%>

<a href="<%=articles_path%>" class="badge badge-dark">Show all articles</a>
<hr/>

<%= form_for [ @article, @article.comments.build ] do |f| %>
  <p>
    <%= f.hidden_field :author, :value => current_user.username%>
  </p>
  <p>
    <%= f.label 'Add new comment:' %><br/>
    <%= f.text_area :body, :class => "form-control"%>
  </p>
  <p>
    <%= f.submit 'Submit', :class => "btn btn-success" %>
  </p>
<% end %>
<%end%>
<% @article.comments.reverse.each do |comment| %>
<div class="alert alert-info" role="alert">
<h4><%=comment.author%></h4>
<div><%=comment.body%></div>
</div>
<%end%>
</div>
</div>
</body>

app/views/contacts/create.html.erb
<h2><%= t('contacts.ok')%></h2>

app/views/contacts/new.html.erb
<h3><%= t('contacts.contact_us') %></h3>

<% if @contact%>
<ul id="contacterrors">
<% @contact.errors.full_messages.each do |er|%>
  <li><%=er%></li>
<%end%>
</ul>
<%end%>

<p>
  <%= form_for :contact, url: '/contacts' do |f|%>
  <label for="contact_email">Email:</label><br/>
  <%= f.text_field :email%>
</p>
<p>
 <label for="contact_message">Your message:</label><br/>
  <%= f.text_area :message%>
</p>
<p>
  <%= f.submit 'Send Message '%>
</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap, JQuery %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/articles">Articles</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/users">Users <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/articles/new">New article</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About Us</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="/contacts">Contact</a>
          </li>
          <li class="nav-item dropdown" style="position: absolute; right: 1%;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%if signed_in?%>
              <%=current_user.username%>
              <%else%>
              <%="Log In"%>
              <%end%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%if signed_in?%>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
              <%else%>
              <%= link_to 'Log In', new_user_session_path, :class => "dropdown-item" %>
              <%end%>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<div class="container">

<div class="list-group">
<%@users.each do |user|%>
<a href="<%=user_path(user)%>" class="list-group-item list-group-item-action list-group-item-primary"><%=user.username%></a>
<%end%>
</div>

</div> <!-- container-->